CREATE TABLE aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(120) NOT NULL ,
    registro_academico CHAR(11) NOT NULL ,
    telefone CHAR(11) NOT NULL ,
    curso VARCHAR(30) NOT NULL,

    CONSTRAINT chk_tamanho_telefone
    CHECK (char_length(telefone) = 11),

    CONSTRAINT chk_tamanho_ra
        CHECK ( char_length(registro_academico) = 10),

    CONSTRAINT chk_curso
    CHECK (curso in (
        'ENFERMAGEM',
        'MEDICINA',
        'DIREITO',
        'TI',
        'EDUCACAO_FISICA',
        'BIOMEDICINA',
        'NUTRICAO',
        'ENGENHARIA',
        'ESTETICA',
        'FISIOTERAPIA',
        'MEDICINA_VETERINARIA')
    )
);

CREATE TABLE equipamentos(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipamento VARCHAR(100) NOT NULL ,
    quantidade INTEGER NOT NULL
);

CREATE TABLE reservas(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    alunos_id BIGINT NOT NULL ,
    horario TIME NOT NULL ,
    data DATE NOT NULL ,
    status VARCHAR(20) NOT NULL ,
    data_criacao_reserva timestamptz NOT NULL ,

    CONSTRAINT chk_status
    CHECK ( status IN (
        'RESERVADO',
        'CANCELADO'
        ) )
);

CREATE TABLE equipamentos_reservados(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    reserva_id BIGINT NOT NULL ,
    equipamento_id BIGINT NOT NULL ,
    quantidade INTEGER NOT NULL ,

    CONSTRAINT fk_equipamentos
        FOREIGN KEY (equipamento_id)
        REFERENCES equipamentos(id),

    CONSTRAINT fk_reserva
        FOREIGN KEY (reserva_id)
        REFERENCES reservas(id)
);